Algoritmo "volei"
// pa
// cintia 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2021
Var
//variaveis
altura,idade:real
competir:logico


Inicio
//entrada
escreval("qual sua altura:")
leia(altura)
escreval("qual sua idade")
leia(idade)
competir <- (altura >1.75)e(idade >18)
escreval("vc pode competir?",competir)



Fimalgoritmo