Algoritmo "areadotriangulo"
// 
//  
// Descrição   : areadotriangulo
// Autor(a)    :joao_pedro
// Data atual  : 01/03/2021
Var
area, base, altura:real


Inicio
//entrada
escreval("digite a base do triangulo")
leia (base)
escreval ("digite a altura do triangulo")
leia(altura)
//processamento
area <- base*altura/2
//saida
escreval("a area do triangulo é: ",area)


Fimalgoritmo