Algoritmo "almento"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2021
Var
hora,min,valor,almento:real

Inicio
escreval("quanto você ganha por hora")
leia(hora)
escreval("e minutos")
leia(min)
escreval("qual a porcentagem do almento")
leia(almento)
//processamento
valor <-(min/60)+hora*1,+almento
//saida
escreval("você ganha isso com o almento:",valor)



Fimalgoritmo