Algoritmo "horas e minutos em decimal"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2021
Var
hora, minuto,valor :real


Inicio
escreval("quantas horas você quer converter")
leia(hora)
escreval("quantos minutos agora")
leia(minuto)
//processamento
valor <-(minuto/60)+ hora
//saida
escreval("aqui esta o resultado:",valor)



Fimalgoritmo