Algoritmo "preço do trabalho"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2021
Var
vt, valor , peca :real


Inicio
//inicio
escreval("qual o valor da peça")
leia(peca)
escreval("valor total da peça")
leia(valor)
//processamento
vt <- valor-peca
//saida
escreval("o valor do tempo é:",vt)
Fimalgoritmo