Algoritmo "ufc"
// pa 
// cintia 

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2021
Var
//variaveis
peso:real

Inicio
//entrada
escreval("qual seu peso:")
leia(peso)

se((peso <47.63)) entao

 escreval("---------------------------------|")
 escreval("você participara do palha ligeiro|")
 escreval("---------------------------------|")


fimse


se((peso <48.99)e(peso>47.6)) entao
escreval(" |---------------------------------|")
escreval(" |    você participara do palha    |")
escreval(" |---------------------------------|")
fimse
se((peso<50.35)e(peso>48.99)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do mosca ligeiro|")
escreval(" |---------------------------------|")
fimse
se((peso<51.71)e(peso>50.35)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do mosca        |")
escreval(" |---------------------------------|")
fimse
se((peso<53.52)e(peso>51.71)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do super mosca  |")
escreval(" |---------------------------------|")
fimse
se((peso<55.34)e(peso>53.52)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do  galo        |")
escreval(" |---------------------------------|")
fimse
se((peso<57.15)e(peso>55.34)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do super galo   |")
escreval(" |---------------------------------|")
fimse
se((peso<58.97)e(peso>57.15)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do pena         |")
escreval(" |---------------------------------|")
fimse
se((peso<61.23)e(peso>58.97)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do super pena   |")
escreval(" |---------------------------------|")
fimse
se((peso<63.5)e(peso>61.23)) entao
escreval("  |---------------------------------|")
escreval("  |você participara do leve         |")
escreval("  |---------------------------------|")
fimse
se((peso<66.68)e(peso>63.5)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do super leve   |")
escreval(" |---------------------------------|")
fimse
se((peso<69.85)e(peso>66.68)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do meio medio   |")
escreval(" |---------------------------------|")
fimse
se((peso<73.03)e(peso>69.85)) entao
escreval(" |------------------------------------|")
escreval(" |você participara do super meio medio|")
escreval(" |------------------------------------|")
fimse
se((peso<76.2)e(peso>73.03)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do medio        |")
escreval(" |---------------------------------|")
fimse
se((peso<79.38)e(peso>76.2)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do super medio  |")
escreval(" |---------------------------------|")
fimse
se((peso<90.72)e(peso>79.38)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do meio pesado  |")
escreval(" |---------------------------------|")
fimse
se((peso>80)e(peso<90.72)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do cruzador     |")
escreval(" |---------------------------------|")
fimse
se((peso>90.72)) entao
escreval(" |---------------------------------|")
escreval(" |você participara do pesado       |")
escreval(" |---------------------------------|")
fimse






Fimalgoritmo
